grading_app/config/routes.rb
Rails.application.routes.draw do

  resources :courses do
    resources :assessmentitems
    
  end
  resources :students
  resources :instructors
  root :to => redirect('/home')
  
    get '/instructor_homepage' => 'sessions#instructor_homepage'
    get '/student_homepage' => 'sessions#student_homepage'
    get  '/login' => 'sessions#new' 
    get  '/home' => 'sessions#home' 
    get '/courses/:course_id/index_students' => 'courses#index_students'
    get '/courses/:course_id/add_student' => 'courses#add_student'
    get '/courses/:course_id/remove_student' => 'courses#remove_student'
    post '/login' => 'sessions#create'
    post '/logout' => 'sessions#destroy'
    get  '/courses/:course_id/student/:student_id/grades' => 'grades#index'
    get  '/courses/:course_id/student/:student_id/grades/new' => 'grades#new'
    post  '/courses/:course_id/student/:student_id/grades' => 'grades#create'
    get  '/courses/:course_id/student/:student_id/grades/:id/edit' => 'grades#edit'
    put  '/courses/:course_id/student/:student_id/grades/:id' => 'grades#update'
    delete  '/courses/:course_id/student/:student_id/grades/:id' => 'grades#destroy'
end

grading_app/app/models/instructor.rb
class Instructor < ActiveRecord::Base
  
  EMAIL_FORMAT= /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  PASSWD_FORMAT= /\A.*(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).*\z/
  validates_uniqueness_of :email
  validates :name, :length => {:maximum => 25}, :presence => true
  validates :surname, :length => {:maximum => 25}, :presence => true
  validates :email, :presence => true, :format => {:with => EMAIL_FORMAT , :message => "email in wrong format"}
  validates :password, :presence => true, :length => {:minimum => 6}, :format => {:with => PASSWD_FORMAT, :message => "wrong password format"}
  
  validates_uniqueness_of :email
  has_many :students, through: :courses
  def matches_password?(password)
      self.password == password
  end
  
end

grading_app/app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  
    before_filter :enforce_login_instructor
      
    
    def edit
        @instructor = @current_user
        @password_mismatch=''

    end
    
    def update
      @instructor = @current_user
     
      if params[:instructor][:password] != params[:instructor][:password1] then
          @password_mismatch = 'Passwords do not match'
          render 'edit'
      
      elsif @instructor.update_attributes(permitted_params) then
        flash[:notice2] = "#{@instructor.email} was successfully updated."
        redirect_to edit_instructor_path(@instructor)
      else
        flash[:notice] = @instructor.errors.full_messages.to_sentence
        render 'edit' 
      end

    end
    
    def permitted_params
        params.require(:instructor)
        params[:instructor].permit(:name, :surname, :email, :password)
    end
    
end

grading_app/app/views/instructors/_instructor_form.html.haml
- unless @instructor.errors.empty?

  #warning

    Errors prevented your profile from being #{controller.action_name}d:

    %ul

      - @instructor.errors.full_messages.each do |error|

        %li= error
        
- unless @password_mismatch.empty?

  #warning

    Errors prevented your profile from being #{controller.action_name}d:
    
    %ul

      %li= @password_mismatch

%table.center
  %tbody
    %tr
      %td
        = label :instructor, :name, 'Instructor Name'
      %td
        = text_field :instructor, 'name'
    %tr
      %td
        = label :instructor, :surname, 'Instructor Surname'
      %td
        = text_field :instructor, 'surname'
    %tr
      %td
        = label :instructor, :email, 'Instructor Email'
      %td    
        = text_field :instructor, 'email', :disabled => true
    %tr
      %td
        = label :instructor, :password, 'Instructor Password'
      %td    
        = password_field :instructor , 'password'
    %tr
      %td
        = label :instructor, :password1, 'Reenter Password'
      %td    
        = password_field :instructor , 'password1'

grading_app/app/views/instructors/edit.html.haml
%h2 Edit Instructor

= form_tag instructor_path(@instructor), :method => :put do
  = render partial: 'instructor_form' 
  = submit_tag 'Save Changes'
=link_to 'Back', instructor_homepage_path