grading_app/config/routes.rb
Rails.application.routes.draw do

  resources :courses do
    resources :assessmentitems
    
  end
  resources :students
  resources :instructors
  root :to => redirect('/home')
  
    get '/instructor_homepage' => 'sessions#instructor_homepage'
    get '/student_homepage' => 'sessions#student_homepage'
    get  '/login' => 'sessions#new' 
    get  '/home' => 'sessions#home' 
    get '/courses/:course_id/index_students' => 'courses#index_students'
    get '/courses/:course_id/add_student' => 'courses#add_student'
    get '/courses/:course_id/remove_student' => 'courses#remove_student'
    post '/login' => 'sessions#create'
    post '/logout' => 'sessions#destroy'
    get  '/courses/:course_id/student/:student_id/grades' => 'grades#index'
    get  '/courses/:course_id/student/:student_id/grades/new' => 'grades#new'
    post  '/courses/:course_id/student/:student_id/grades' => 'grades#create'
    get  '/courses/:course_id/student/:student_id/grades/:id/edit' => 'grades#edit'
    put  '/courses/:course_id/student/:student_id/grades/:id' => 'grades#update'
    delete  '/courses/:course_id/student/:student_id/grades/:id' => 'grades#destroy'
end

grading_app/app/models/student.rb
class Student < ActiveRecord::Base
  
  EMAIL_FORMAT= /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  PASSWD_FORMAT= /\A.*(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).*\z/
  validates :name, :length => { :maximum => 30}, :presence => true
  validates :surname, :length => { :maximum => 30}, :presence => true
  validates_uniqueness_of :email
  validates :email, :presence => true, :format => {:with => EMAIL_FORMAT, :message => "wrong email"}
  validates :password, :presence => true, :length => {:minimum => 8}, :format => {:with => PASSWD_FORMAT, :message => " wrong format"}
  
  has_many :grades
  has_and_belongs_to_many :courses
  has_many :instructors, through: :courses
  
  def matches_password?(password)
      self.password == password
  end
  
end

grading_app/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
    
    before_filter :enforce_login_instructor 
    def index
        @students = Student.all
    end
    
    def show
        id = params[:id]
        @student =Student.find id
    end
    
    def new
    end
    
    def create
      @student = Student.new(permitted_params)
      @student.valid?
      if @student.save
        flash[:notice2] = "#{@student.name + " " + @student.surname} was successfully created."
        redirect_to students_path
      else
        flash[:notice] = @student.errors.full_messages.to_sentence
        render 'new' 
      end    
    end
    
    def edit
        @student = Student.find params[:id]
    end
    
    def update
      @student = Student.find params[:id]
      @student.valid?
      if @student.update_attributes(permitted_params)
        flash[:notice2] = "#{@student.email} was successfully updated."
        redirect_to student_path(@student)
      else
        flash[:notice] = @student.errors.full_messages.to_sentence
        render 'edit' 
      end

    end
    
    def destroy 
        id = params[:id]
        @student = Student.find(id)
        @student.destroy
        flash[:warning] = "#{@student.email} was succesfully deleted!"
        redirect_to students_path
    end
    
    def permitted_params
        params.require(:student)
        params[:student].permit(:name, :surname, :email, :password)
    end
end

grading_app/app/views/students/_student.html.haml
-# Single row of Students
%tr
  %td= student.name 
  %td= student.surname
  %td= link_to " More about #{student.name}", student_path(student)

grading_app/app/views/students/_student_form.html.haml
%table.center
  %tbody
    %tr
      %td
        = label :student, :name, 'Student Name'
      %td
        = text_field :student, 'name'
    %tr
      %td
        = label :student, :surname, 'Student Surname'
      %td
        = text_field :student, 'surname'
    %tr
      %td
        = label :student, :email, 'Student Email'
      %td    
        = text_field :student, 'email'
    %tr
      %td
        = label :student, :password, 'Student Password'
      %td    
        = password_field :student , 'password'

grading_app/app/views/students/edit.html.haml
%h2 Edit Student

= form_tag student_path(@student), :method => :put do
  = render partial: 'student_form' 
  = submit_tag 'Save Changes'
= link_to 'Back to student list', students_path

grading_app/app/views/students/index.html.haml
-#  This file is app/views/students/index.html.haml
%h1 Students

%table#students.center
  %thead
    %tr
      %th Name
      %th Surname 
  %tbody
  = render partial: 'student', collection: @students

%p  
'
= link_to 'Add new Student', new_student_path
' | '
= link_to 'Back to homepage', instructor_homepage_path
'

grading_app/app/views/students/new.html.haml
-# Single row of Students
%h2 Add New Student

= form_tag students_path, :method => :post do
  = render partial: 'student_form'
  = submit_tag 'Add Student'
  
= link_to 'Back', students_path

grading_app/app/views/students/show.html.haml
-# in app/views/students/show.html.haml
%h2 Details: #{@student.name}

%ul#details
  %li
    Student name:
    = @student.name
  %li
    Student Surname:
    = @student.surname
  %li
    Student Email:
    = @student.email



= link_to 'Edit', edit_student_path(@student)
= button_to 'Delete', student_path(@student), :method => 'delete', :data => {:confirm => 'Are you sure?'} 
-#= link_to 'Add Student', new_course_student_path(@course)
-#= link_to 'Add Assessment Item', new_course_assessmentitem_path(@course)
= link_to 'Back to student list', students_path