grading_app/config/routes.rb
Rails.application.routes.draw do

  resources :courses do
    resources :assessmentitems
    
  end
  resources :students
  resources :instructors
  root :to => redirect('/home')
  
    get '/instructor_homepage' => 'sessions#instructor_homepage'
    get '/student_homepage' => 'sessions#student_homepage'
    get  '/login' => 'sessions#new' 
    get  '/home' => 'sessions#home' 
    get '/courses/:course_id/index_students' => 'courses#index_students'
    get '/courses/:course_id/add_student' => 'courses#add_student'
    get '/courses/:course_id/remove_student' => 'courses#remove_student'
    post '/login' => 'sessions#create'
    post '/logout' => 'sessions#destroy'
    get  '/courses/:course_id/student/:student_id/grades' => 'grades#index'
    get  '/courses/:course_id/student/:student_id/grades/new' => 'grades#new'
    post  '/courses/:course_id/student/:student_id/grades' => 'grades#create'
    get  '/courses/:course_id/student/:student_id/grades/:id/edit' => 'grades#edit'
    put  '/courses/:course_id/student/:student_id/grades/:id' => 'grades#update'
    delete  '/courses/:course_id/student/:student_id/grades/:id' => 'grades#destroy'
end

grading_app/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  
    
    before_filter :enforce_login_instructor , except: [:index] 
    
    def index
        @courses = Course.all
    end
    
    def show
        @id = params[:id]
        @course = Course.find params[:id]
    end
    
    def new
     
    end
    
    def create
      @course = Course.new(permitted_params)
      if @course.save
        flash[:notice2] = "#{@course.name} was successfully created."
        redirect_to courses_path
      else
        flash[:notice] = @course.errors.full_messages.to_sentence
        render 'new' 
      end    
    end
    
    def edit
        @course = Course.find params[:id]
    end
    
    def update
      @course = Course.find params[:id]
      if @course.update_attributes(permitted_params)
        flash[:notice2] = "#{@course.name} was successfully updated."
        redirect_to course_path(@course)
      else
        flash[:notice] = @course.errors.full_messages.to_sentence
        render 'edit' # note, 'edit' template can access @course's field values!
      end

    end
    
    def destroy 
        id = params[:id]
        @course = Course.find(id)
        @course.destroy
        flash[:warning2] = "#{@course.name} was succesfully deleted!"
        redirect_to courses_path
    end
    
    def index_students
        id = params[:course_id]
        @course = Course.find id
        @students= @course.students
        @allstudents=Student.all - @students
    end
    
    def add_student
        id = params[:course_id]
        @course = Course.find id
        student = Student.find params[:student]
        @course.students << student
        redirect_to '/courses/'+id+'/index_students'
    end
    
    def remove_student
        id = params[:course_id]
        @course = Course.find id
        student = params[:data]
        @course.students.delete(student)
        redirect_to '/courses/'+id+'/index_students'
    end
    
    def permitted_params
        params.require(:course)
        params[:course] [:instructor_id]=@current_user.id
        params[:course].permit(:code, :name, :semester_offered, :catalog_data, :instructor_id)
    end
    
end

grading_app/app/views/courses/_course.html.haml
-# A single row of the All Courses table
%tr
  %td= course.code 
  %td= course.name
  %td= course.semester_offered
  %td= course.catalog_data
  - if @current_user  
    %td= link_to "More", course_path(course)
  -else
    %td= link_to 'Assessment Items', course_assessmentitems_path(course)

grading_app/app/views/courses/_course_form.html.haml
%table.center
  %tbody
    %tr
      %td
        = label :course, :code, 'Course Code'
      %td
        = text_field :course, 'code'
    %tr
      %td
        = label :course, :name, 'Course Name'
      %td
        = text_field :course, 'name'
    %tr
      %td
        = label :course, :semester_offered, 'Semester Offered'
      %td    
        = text_field :course, 'semester_offered'
    %tr
      %td
        = label :course, :catalog_data, 'Catalog Data'
      %td    
        = text_area :course, 'catalog_data'

grading_app/app/views/courses/_student.html.haml
-# A single row of the All Students table
%tr
  %td= student.name 
  %td= student.surname
  %td= link_to 'Remove' , :controller => 'courses', :action => 'remove_student', :data => student 
  %td= link_to 'Grades' , :controller => 'grades', :action => 'index', :student_id => student.id

grading_app/app/views/courses/edit.html.haml
%h2 Edit Course

= form_tag course_path(@course), :method => :put do
  = render partial: 'course_form' 
  = submit_tag 'Save Changes'
= link_to 'Back to course list', courses_path

grading_app/app/views/courses/index.html.haml
-#  This file is app/views/courses/index.html.haml
%h1 All Courses

%table#courses.center
  %thead
    %tr
      %th Code 
      %th Name 
      %th Semester 
      %th Catalog 
  %tbody
  = render partial: 'course', collection: @courses
  
- if @current_user
  %p
  '
  = link_to 'Add new course', new_course_path
  ' | '
  = link_to 'Back to homepage', instructor_homepage_path
  '

grading_app/app/views/courses/index_students.html.haml
-#  This file is app/views/students/index.html.haml
%h1 All Students of #{@course.name}

%table#students.center
  %thead
    %tr
      %th Name
      %th Surname 
  %tbody
  = render partial: 'student', collection: @students
  
%p
= form_tag '/courses/'+params[:course_id] +'/add_student', :method => :get do
  = select_tag :student , options_from_collection_for_select(@allstudents, "id", "name")
  - if @allstudents.empty? then val=true  end
  = submit_tag "Add Student" , disabled: val
= link_to "Back", course_path(@course)

grading_app/app/views/courses/new.html.haml
%h2 Create New Course

= form_tag courses_path, :method => :post do
  = render partial: 'course_form' 
  = submit_tag 'Create Course'
= link_to 'Back', courses_path

grading_app/app/views/courses/show.html.haml
-# in app/views/courses/show.html.haml
%h2 #{@course.name}

%ul#details
  %li
    Code:
    = @course.code
  %li
    Name:
    = @course.name
  %li
    Semester Offered:
    = @course.semester_offered

%h3 Catalog Data:

%p#description= @course.catalog_data


= link_to 'Edit', edit_course_path(@course)
= button_to 'Delete', course_path(@course), :method => 'delete', :data => {:confirm => 'Are you sure?'} 

'
= link_to 'Show Assessment Items', course_assessmentitems_path(@course)
' | '
= link_to 'Show Students', @id+'/index_students'
' | '
= link_to 'Back to course list', courses_path
'