grading_app/config/routes.rb
Rails.application.routes.draw do

  resources :courses do
    resources :assessmentitems
    
  end
  resources :students
  resources :instructors
  root :to => redirect('/home')
  
    get '/instructor_homepage' => 'sessions#instructor_homepage'
    get '/student_homepage' => 'sessions#student_homepage'
    get  '/login' => 'sessions#new' 
    get  '/home' => 'sessions#home' 
    get '/courses/:course_id/index_students' => 'courses#index_students'
    get '/courses/:course_id/add_student' => 'courses#add_student'
    get '/courses/:course_id/remove_student' => 'courses#remove_student'
    post '/login' => 'sessions#create'
    post '/logout' => 'sessions#destroy'
    get  '/courses/:course_id/student/:student_id/grades' => 'grades#index'
    get  '/courses/:course_id/student/:student_id/grades/new' => 'grades#new'
    post  '/courses/:course_id/student/:student_id/grades' => 'grades#create'
    get  '/courses/:course_id/student/:student_id/grades/:id/edit' => 'grades#edit'
    put  '/courses/:course_id/student/:student_id/grades/:id' => 'grades#update'
    delete  '/courses/:course_id/student/:student_id/grades/:id' => 'grades#destroy'
end

grading_app/app/models/assessmentitem.rb
class Assessmentitem < ActiveRecord::Base
  
  validates :name, :presence => true, :length => {:maximum => 30}
  validates :weight, :presence => true, :inclusion => {:in => '0.0'..'1.0'}
  belongs_to :course
  has_many :grades

  def max_min_grade
    result=Hash.new
    mygrades=Array.new
    sum=0.0
    self.grades.each do |current_grade|
      mygrades<<current_grade.grade
      sum+=current_grade.grade.to_f
    end
    result[:max] = mygrades.max
    result[:min] = mygrades.min
    result[:avg] = sum/self.grades.size
    result
  end
end

grading_app/app/controllers/assessmentitems_controller.rb
class AssessmentitemsController < ApplicationController
  before_filter :has_user_and_course, except: [:index]
  before_filter :enforce_login_instructor,  except: [:index]
  protected
  def has_user_and_course
    unless @current_user
      flash[:warning] = 'Login to create an assessment item.'
      redirect_to '/login'
    end
    unless ( @course = Course.find(params[:course_id]) )
      flash[:warning] = 'Assessment Item must be for an existing course.'
      redirect_to courses_path
    end
  end

  private
  def assessmentitem_params
    params.require(:assessmentitem)
    params[:assessmentitem].permit(:name,:weight,:course_id)        
  end

   public
    def index
      @course = Course.find(params[:course_id])
      @assessmentitems = Assessmentitem.where(:course_id => params[:course_id]  )
      
    end

  public
  def new
    @assessmentitem = @course.assessmentitems.build
  end
  
  def create
    @course.assessmentitems.create(assessmentitem_params)
    redirect_to course_assessmentitems_path(@course)
    
  end
  
  def destroy
        id = params[:id]
        @assessmentitem = Assessmentitem.find(id)
        @assessmentitem.destroy
        flash[:warning2] = "#{@assessmentitem.name} was succesfully deleted!"
        redirect_to course_assessmentitems_path(@course)
  end
  
    def edit
        @assessmentitem = Assessmentitem.find params[:id]
    end
    
    def update
      @assessmentitem = Assessmentitem.find params[:id]
      if @assessmentitem.update_attributes(permitted_params)
        flash[:notice2] = "#{@assessmentitem.name} was successfully updated."
        redirect_to course_assessmentitems_path(@course)
      else
        flash[:notice] = @assessmentitem.errors.full_messages.to_sentence
        render 'edit' # note, 'edit' template can access @course's field values!
      end
    end
    
     def permitted_params
        params.require(:assessmentitem)
        params[:assessmentitem] [:course_id]=@course.id
        params[:assessmentitem].permit(:name, :weight, :course_id)
     end
end

grading_app/app/views/assessmentitems/_assessmentitem_form.html.haml
%table.center
  %tbody
    %tr
      %td
        = label :assessmentitem, :name, 'Name'
      %td
        = text_field :assessmentitem, 'name'
    %tr
      %td
        = label :assessmentitem, :weight, 'Weight'
      %td
        = text_field :assessmentitem, 'weight'
        
%p

grading_app/app/views/assessmentitems/edit.html.haml
%h2 Edit Assessment Item #{@assessmentitem.name} for #{@course.name}

= form_tag course_assessmentitem_path(@course,@assessmentitem), :method => :put do
  = render partial: 'assessmentitem_form' 
  = submit_tag 'Save Changes'
= link_to 'Back to course list', courses_path

grading_app/app/views/assessmentitems/index.html.haml
-#  This file is app/views/assessmentitems/index.html.haml
%h1 All Assessment Items for #{@course.name}

%table.center

  %thead 
    %tr
      %th Name
      %th Weight
      %th Max Grade
      %th Min Grade
      %th Avg Grade
  %tbody 
  - @assessmentitems.each do |assessmentitem|
    %tr
      %td #{assessmentitem.name}
      %td #{assessmentitem.weight}
      %td #{assessmentitem.max_min_grade[:max]}
      %td #{assessmentitem.max_min_grade[:min]}
      %td #{assessmentitem.max_min_grade[:avg]}
      - if @current_user 
        %td= link_to 'Delete', course_assessmentitem_path(@course,assessmentitem), :method => 'delete', :data => {:confirm => 'Are you sure?'}
        %td= link_to 'Edit', edit_course_assessmentitem_path(@course,assessmentitem), :method => 'get'
- if @current_user
  %p
  '
  = link_to 'Add Assessment Item', new_course_assessmentitem_path(@course)
  ' | '
  = link_to 'Back to courses', courses_path
  '

grading_app/app/views/assessmentitems/new.html.haml
%h1 New Assessment Item for #{@course.name}

= form_tag course_assessmentitems_path(@course) do
  = render partial: 'assessmentitem_form'
  = submit_tag 'Create Assessment Item'
= link_to 'Back to course list', courses_path